### ISSUE TITLE
Limit base attacked notifications to when damage is above certain threshold/structure health remaining below a certain threshold

### ISSUE THREAD

**Issue by seanbyrne88** [seanbyrne88/RustPlugins#3]

**Comment by nerdalertdk** [comment]
Uhh yes would like this

**Comment by seanbyrne88** [comment]
Closing this with https://github.com/seanbyrne88/RustPlugins/commit/7b9f108fc01e6fe988330c3a195a9dec11610890#diff-6d6a99939cde01049cc387260faaf1e5
