### ISSUE TITLE
provide a guide or documentation on setting this up with discord?

### ISSUE THREAD

**Issue by mikedevita** [seanbyrne88/RustPlugins#5]
I'm looking to get this setup for a rust server im running and I'm not sure how to setup the rust bot and get it working properly. I get 401 unauthorized when a player tries to join/disconnect.

**Comment by Bobakanoosh** [comment]
I've got a guide I made here, plus a small plugin for a /report command which integrates with the plugin: http://oxidemod.org/plugins/discordreport.2323/

**Comment by mikedevita** [comment]
Thanks man I saw your reply to me on the oxide forums! Ill check it out ☺

**Comment by seanbyrne88** [comment]
Thanks Bobakanoosh! This is a better guide than what I've noted in my documentation. If you don't mind I'd like to link to yours and credit you for it?

**Comment by Bobakanoosh** [comment]
Yea for sure

**Comment by mikedevita** [comment]
agreed 👍 that's the guide I ended up using along with @Bobakanoosh's bot.

[Bobakanoosh/RustNotifierBot](https://github.com/Bobakanoosh/RustNotifierBot)
